apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gitlab
  namespace: flux-system
spec:
  interval: 1h0s
  url: https://charts.gitlab.io

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gitlab-runner
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      version: 0.49.2
  interval: 1h0s
  releaseName: gitlab-runner
  values:
    runners:
      privileged: true
      image: gitlab/gitlab-runner:ubuntu
      serviceAccount:
        create: true
        name: runner
      rbac:
        create: true
        clusterWideAccess: true
      customConfig:
        concurrent: 10
        check_interval: 0
      runners:
        - name: "runner"
          executor: "kubernetes"
          namespace: "default"
          
