apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-cloudflare
  namespace: cert-manager
spec:
  acme:
    email: $(CLOUDFLARE_EMAIL)
    privateKeySecretRef:
      name: letsencrypt-prod-cloudflare
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          email: $(CLOUDFLARE_EMAIL)
          apiKeySecretRef:
            name: cloudflare-api-key
            key: api-key
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
stringData:
  api-key: $(CLOUDFLARE_API_KEY)
type: Opaque
