apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key-secret
type: Opaque
stringData:
  api-key: ${CLOUDFLARE_API_KEY} 

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${CLOUDFLARE_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        cloudflare:
          email: ${CLOUDFLARE_EMAIL}
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
---
apiVersion: cert-manage
kind: OriginIssuer
metadata:
  name: cloudflare-issuer
  namespace: kube-system
spec:
  signatureType: OriginECC
  auth:
    serviceKeyRef:
      name: service-key
      key: key

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sredevops-cl
  namespace: kube-system
spec:
  # The secret name where cert-manager
  # should store the signed certificate.
  secretName: sredevops-cl-tls
  dnsNames:
    - sredevops.cl
    - "*.sredevops.cl"
  # Duration of the certificate.
  duration: 168h
  # Renew a day before the certificate expiration.
  renewBefore: 24h
  # Reference the Origin CA Issuer you created above,
  # which must be in the same namespace.
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: OriginIssuer
    name: cloudflare-issuer
---
apiVersion: networking/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: cloudflare-issuer
    cert-manager.io/issuer-kind: OriginIssuer
    cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
  name: ingress-cloudflare
  namespace: kube-system
spec:
  rules:
    - host: oci.sredevops.cl
      http:
        paths:
          - backend:
              serviceName: Kubernetes
              servicePort: 443
            path: /
  tls:
    # specifying a host in the TLS section will tell cert-manager 
    # what DNS SANs should be on the created certificate.
    - hosts:
        - sredevops.cl
      # cert-manager will create this secret
      secretName: sredevops-cl-tls
