apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gitlab
  namespace: flux-system
spec:
  interval: 1h0s
  url: https://charts.gitlab.io

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
  chart:
    spec:
      chart: gitlab-runner
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      version: latest
  interval: 1h0s
  releaseName: gitlab-runner
  values:
